spring:
  application:
    name: server-a
  datasource:
    url: jdbc:mysql://localhost:3306/server_a_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
