spring:
  application:
    name: server-a
  datasource:
    url: jdbc:mysql://localhost:3306/server_a_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: promotion
    password: promotion

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health

promotion:
  rabbitmq:
    issue-requested:
      exchange: issue.requested.exchange
      routing-key: issue.requested
  outbox-relay:
    enabled: true
    fixed-delay-ms: 1000
    initial-delay-ms: 5000
